// <auto-generated />
using LineNotifyPractice.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LineNotifyPractice.Migrations
{
    [DbContext(typeof(SubscriberContext))]
    [Migration("20220406013642_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LineNotifyPractice.Models.DB.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LINELoginAccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LINELoginRefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LINENotifyAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("LINEUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
